version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      # Environnement Java 8 ou supérieur
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout # Récupère le code du repository

      - run: # Install les dependences
          name: Setup Maven Project
          command: mvn dependency:go-offline --batch-mode

      - run:
          name: Build Project
          command: mvn clean compile

      - run: # Execution des tests unitaires et génération du rapport Jacoco
          name: Run Tests & Generate Reports
          command: mvn clean test

      - codecov/upload

      - run:
          name: Generate Javadoc
          command: mvn clean javadoc:javadoc

      - run:
          name: Deploy Javadoc to GitHub Pages
          command: |
            if [[ "$CIRCLE_BRANCH" == "gh-pages" ]]; then
              echo "Skip build circleci on gh-pages branch.";
              exit 0;
            fi
            mvn -B -DskipTests clean package

      - run:
          name: Generate Javadoc
          command: mvn -B javadoc:javadoc


workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
        filters:
          branches:
            only: master
