version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      # Environnement Java 8 ou supérieur
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout # Récupère le code du repository

      - run: # Install les dependences
          name: Setup Maven Project
          command: mvn dependency:go-offline --batch-mode

      - run:
          name: Build Project
          command: mvn clean compile

      - run: # Execution des tests unitaires et génération du rapport Jacoco
          name: Run Tests & Generate Reports
          command: mvn clean test

      - codecov/upload

      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check
      - run:
          name: Publish checkstyle badge to GitHub
          command: |
            git config --global user.email "gaspardarosafrancisco@gmail.com"
            git config --global user.name "Gasparfgf"
            git config --global push.autoSetupRemote true
            git add docs/
            if git diff-index --quiet HEAD --; then
              echo "No changes to commit, skipping git commit and push."
            else
              git commit -am "Update Checkstyle badge"
              git push
            fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
        filters:
          branches:
            # Branche master uniquement
            only: master