version: 2.1

jobs:
  build:
    docker:
      # Environnement Java 8 ou supérieur
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout # Récupère le code du repository

      - run: # Install les dependences
          name: Setup Maven Project
          command: mvn dependency:go-offline --batch-mode

      - run:
          name: Build Project
          command: mvn clean compile

      - run: # Execution des tests unitaires
          name: Run Tests
          command: mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
        filters:
          branches:
            # Branche master uniquement
            only: master
