version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      # Environnement Java 8 ou supérieur
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout # Récupère le code du repository

      - run: # Install les dependences
          name: Setup Maven Project
          command: mvn dependency:go-offline --batch-mode

      - run:
          name: Build Project
          command: mvn clean compile

      - run: # Execution des tests unitaires et génération du rapport Jacoco
          name: Run Tests & Generate Reports
          command: mvn clean test

      - codecov/upload

      - git config --global user.name "gasparfgf"
        git config --global user.email "gaspardarosafrancisco@gmail.com"
        mkdir -p /tmp/gh-pages
        git clone https://github.com/gasparfgf/ceri-m1-techniques-de-test.git /tmp/gh-pages
        cd /tmp/gh-pages
        if ! git show-ref --quiet refs/heads/gh-pages; then
        git checkout --orphan gh-pages
        git rm -rf .
        echo "Initial commit for gh-pages" > index.html
        git add index.html
        git commit -m "Create gh-pages branch"
        git push origin gh-pages
        fi
        cd -
        
        cp -R target/site/apidocs/* /tmp/gh-pages/
        cd /tmp/gh-pages
        git add .
        git commit -m "Update JavaDoc"
        git push origin gh-pages

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
        filters:
          branches:
            # Branche master uniquement
            only: master